project:
  type: website

website:
  title: "All-topology two-fluid model"
  sidebar:
    search: false
    style: "docked"
    header: |
      <div class="sidebar-logo">
        <img src="/images/logo_HPCatMaths_blanc.png" alt="Logo" height="80">
      </div>
    contents:
      - file: 1D_RIEMANN/post_process_1D_Riemann.ipynb
  page-footer:
    center: |
      <div class="page-logos">
        <img src="/images/logo_samurai.png" alt="Logo 1" height="60">
        <img src="/images/logo_IPP.png" alt="Logo 2" height="60">
      </div>


format:
  html:
    toc: false
    theme:
      - cosmo
      - brand
    css: styles.css
